### PR TITLE
fix privilege name

### PR DESCRIPTION
**Pull request by zeuner**

### CODE REVIEW

**Comment by octacian** [comment]
hmm, When I renamed the chatcommand to `vanish`, I renamed the privilege as well. I suppose that the name `invisibility` would technically be correct though..

**Comment by octacian** [comment]
Could you also update the README where the `vanish` privilege is mentioned near the end?

**Comment by zeuner** [comment]
Thanks for pointing this out. Pushed.

original message follows:

**Comment by octacian** [comment]
Hmmm, thank you for your pull request, but I'm afraid that I prefer the current privilege name. It ensures that there is consistency and that there can be no confusion as to the relation of the command and privilege. If there was more tied to the privilege, I would definitely consider calling it `invisibility` instead.

Thanks again for your interest!

**Comment by zeuner** [comment]
No objections with having a different naming preference.

However, the point of requesting the pull was to make the mod work at
all, since the registered privilege name did not match the required
privilege name in "register_chatcommand".

I don't care whether it is fixed as I suggested, or rather as in
LoneWolfHT's pull request from September.

I'm glad your source tree works now, and keep up the great work!

original message follows:

**Comment by octacian** [comment]
Alright, sorry I didn't notice that originally. Glad to hear it works though, and once more, thanks for your interest! :stuck_out_tongue:

**Pull request closed without merging**
